services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318" # OTLP HTTP
    depends_on:
      - jaeger
    networks:
      - go_boilerplate_external_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # Jaeger collector port
    networks:
      - go_boilerplate_external_network

networks:
  go_boilerplate_external_network:
    name: go_boilerplate_external_network
